---
- include_vars: ../../../group_vars/java.yml
- include_vars: ../../../group_vars/user_vars.yml

- include: default_java.yml
  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos") and (not external_java)
- include: external_java.yml
  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos") and (external_java)
