---
- include_vars: ../../../group_vars/db_server.yml
- include_vars: ../../../group_vars/user_vars.yml

- include: mariadb.yml
  when: database_type == "mysql"
- include: postgresql.yml
  when: database_type == "postgresql"
